---
engine_version: 0.4.26
file_version: 2024-03-17 15:49:22.204422000 -05:00
resources:
  - name: user
    preferences:
      columns:
        - access_type: hidden
          name: reset_password_sent_at
        - access_type: hidden
          name: remember_created_at
        - access_type: hidden
          name: uid
    updated_at: 2024-03-17 15:47:21.763506000 +00:00
configs:
  - key: header.links
    value: []
    updated_at: 2024-03-17 15:19:22.204422000 +00:00
queries: []
dashboards: []
forms: []
alerts: []
api_configs:
  - id: 1
    name: origin
    url: "/"
    preferences: {}
    description:
    updated_at: 2024-03-17 02:44:24.675578000 +00:00
