---
engine_version: 0.4.26
file_version: 2024-03-18 09:35:04.676697000 -05:00
resources:
  - name: book
    preferences:
      columns:
        - format:
            currency: PEN
            currency_base: units
          name: price
      scopes:
        - visible: false
          name: filter_by_author
        - visible: false
          name: filter_by_category
        - visible: false
          name: filter_by_editorial
        - visible: false
          name: search
    updated_at: 2024-03-18 09:34:16.312296000 +00:00
  - name: cart
    preferences:
      visible: false
    updated_at: 2024-03-18 09:33:12.408603000 +00:00
  - name: order_detail
    preferences:
      visible: false
    updated_at: 2024-03-18 09:33:18.715591000 +00:00
  - name: orderable
    preferences:
      visible: false
    updated_at: 2024-03-18 09:33:19.615096000 +00:00
  - name: user
    preferences:
      columns:
        - access_type: hidden
          name: reset_password_sent_at
        - access_type: hidden
          name: remember_created_at
        - access_type: hidden
          name: uid
    updated_at: 2024-03-17 15:47:21.763506000 +00:00
configs:
  - key: header.links
    value:
      - name: Reportes
        link_type: reports
      - name: Formularios
        link_type: forms
    updated_at: 2024-03-18 09:35:04.676697000 +00:00
queries: []
dashboards: []
forms: []
alerts: []
api_configs:
  - id: 1
    name: origin
    url: "/"
    preferences: {}
    description:
    updated_at: 2024-03-17 17:20:32.087128000 +00:00
